apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-dvoqtgam
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-dvoqtgam:ce9e66e463e2067eb240259a0dc4d5648cd39432@sha256:02eea893d46c0a52c4b5ed14109912e80a7ce5f8064951fd4b49bfe175769171
          name: container-image
